version: "3.8"
services:
  remote-proxy:
    image: ghcr.io/sagernet/sing-box
    container_name: remote-proxy
    # restart: unless-stopped
    ports:
      - "0.0.0.0:1080:1080/tcp"
      - "0.0.0.0:3128:3128/tcp"
    volumes:
      - ./singbox.json:/etc/sing-box/config.json:ro
    command: ["run", "-c", "/etc/sing-box/config.json"]
